from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_TARGETS = [
    {"framework_version": "4.7", "framework_moniker": "net47", "platform": "Any"},
]
MSBUILD_PLATFORM_MAP = {"Any": "Any CPU", "x86": "x86", "x64": "x64"}
PLATFORM_TARGET_MAP = {"Any": "AnyCPU", "x86": "x86", "x64": "x64"}
README_START = "<!-- build-status:start -->"
README_END = "<!-- build-status:end -->"


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def parse_args() -> argparse.Namespace:
    script_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Manage configurable build branches and status summaries."
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=script_root / "build-config.json",
        help="Configuration file stored on the main branch.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    matrix_parser = subparsers.add_parser("matrix", help="Emit the GitHub Actions build matrix.")
    matrix_parser.add_argument(
        "--github-output",
        type=Path,
        help="Optional GitHub output file that will receive the matrix JSON.",
    )

    sync_parser = subparsers.add_parser("sync-tools", help="Clone configured tool repositories.")
    sync_parser.add_argument(
        "--tools-dir",
        type=Path,
        default=script_root / "tools",
        help="Directory where configured tools should be cloned.",
    )
    sync_parser.add_argument(
        "--status-file",
        type=Path,
        help="Previous status file used to detect upstream updates.",
    )
    sync_parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="JSON file that will receive the synchronized tool metadata.",
    )

    branch_parser = subparsers.add_parser(
        "branch-readme", help="Generate a README for a binary output branch."
    )
    branch_parser.add_argument(
        "--result-json",
        type=Path,
        required=True,
        help="Build result JSON generated by scripts/build_dotnet_tools.py.",
    )
    branch_parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="README file to write into the output branch directory.",
    )

    aggregate_parser = subparsers.add_parser(
        "aggregate", help="Aggregate branch results into build-status.json and README.md."
    )
    aggregate_parser.add_argument(
        "--results-dir",
        type=Path,
        required=True,
        help="Directory that contains branch result JSON files.",
    )
    aggregate_parser.add_argument(
        "--status-output",
        type=Path,
        required=True,
        help="Path to write the aggregated build status JSON.",
    )
    aggregate_parser.add_argument(
        "--readme",
        type=Path,
        required=True,
        help="README.md on the main branch to update.",
    )
    aggregate_parser.add_argument(
        "--previous-status",
        type=Path,
        help="Existing build-status.json file for preserving comparison metadata.",
    )

    return parser.parse_args()


def load_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_config(config_path: Path) -> dict[str, object]:
    config = load_json(config_path)
    config.setdefault("tools", [])
    config.setdefault("targets", DEFAULT_TARGETS)
    return config


def sanitize_branch_name(value: str) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9._/-]+", "_", value.strip())
    sanitized = sanitized.lstrip(".")
    sanitized = sanitized.replace("..", ".")
    sanitized = sanitized.strip("/.")
    if not sanitized:
        raise ValueError(f"Invalid branch name derived from {value!r}")
    return sanitized


def normalize_target(target: dict[str, object]) -> dict[str, str]:
    framework_version = str(target["framework_version"])
    framework_moniker = str(target["framework_moniker"])
    platform = str(target["platform"])
    display_name = str(target.get("display_name") or f".NET_{framework_version}_{platform}")
    branch = sanitize_branch_name(str(target.get("branch") or display_name))
    msbuild_platform = str(target.get("msbuild_platform") or MSBUILD_PLATFORM_MAP.get(platform, platform))
    platform_target = str(target.get("platform_target") or PLATFORM_TARGET_MAP.get(platform, platform))
    return {
        "framework_version": framework_version,
        "framework_moniker": framework_moniker,
        "platform": platform,
        "display_name": display_name,
        "branch": branch,
        "msbuild_platform": msbuild_platform,
        "platform_target": platform_target,
    }


def configured_targets(config: dict[str, object]) -> list[dict[str, str]]:
    return [normalize_target(target) for target in config.get("targets", DEFAULT_TARGETS)]


def configured_tools(config: dict[str, object]) -> list[dict[str, object]]:
    tools = []
    for tool in config.get("tools", []):
        if tool.get("enabled", True):
            tools.append(tool)
    return tools


def run_git(*args: str, cwd: Path | None = None) -> str:
    completed = subprocess.run(
        ["git", *args],
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip()


def previous_tool_status(status_file: Path | None) -> dict[str, dict[str, object]]:
    if not status_file or not status_file.exists():
        return {}
    data = load_json(status_file)
    tools = data.get("tools", [])
    if not isinstance(tools, list):
        return {}
    return {
        str(tool.get("name")): tool
        for tool in tools
        if isinstance(tool, dict) and tool.get("name")
    }


def sync_tools(config_path: Path, tools_dir: Path, status_file: Path | None, output_path: Path) -> int:
    config = load_config(config_path)
    tools = configured_tools(config)
    previous = previous_tool_status(status_file)
    if tools_dir.exists():
        shutil.rmtree(tools_dir)
    tools_dir.mkdir(parents=True, exist_ok=True)

    synchronized_tools: list[dict[str, object]] = []
    for tool in tools:
        name = str(tool["name"])
        repository = str(tool["repository"])
        ref = str(tool.get("ref") or tool.get("branch") or "HEAD")
        destination = tools_dir / name

        clone_command = ["clone", "--depth", "1"]
        if ref != "HEAD":
            clone_command.extend(["--branch", ref])
        clone_command.extend([repository, str(destination)])
        run_git(*clone_command)

        latest_revision = run_git("rev-parse", "HEAD", cwd=destination)
        previous_revision = str(previous.get(name, {}).get("latest_revision") or "")
        synchronized_tools.append(
            {
                "name": name,
                "repository": repository,
                "ref": ref,
                "source_path": str(destination),
                "latest_revision": latest_revision,
                "previous_revision": previous_revision,
                "updated": latest_revision != previous_revision if previous_revision else True,
            }
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps({"generated_at": utc_now(), "tools": synchronized_tools}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return 0


def build_result_rows(result: dict[str, object]) -> list[str]:
    rows = [
        "| 项目 | 状态 | 输出文件数 | 详情 |",
        "| --- | --- | ---: | --- |",
    ]
    for item in result.get("results", []):
        status = "成功" if item.get("status") == "success" else "失败"
        detail = str(item.get("error") or "-")
        rows.append(
            f"| {item.get('project', '-')} | {status} | {item.get('copied_files', 0)} | {detail} |"
        )
    return rows


def write_branch_readme(result_json: Path, output_path: Path) -> int:
    result = load_json(result_json)
    lines = [
        f"# {result.get('branch_display_name') or result.get('branch_name') or '构建结果'}",
        "",
        f"- Git 分支：`{result.get('branch_name') or '未命名'}`",
        f"- 显示名称：`{result.get('branch_display_name') or result.get('branch_name') or '未命名'}`",
        f"- 最后构建时间：`{result.get('generated_at')}`",
        f"- 构建状态：`{result.get('summary', {}).get('status', 'unknown')}`",
        f"- 目标框架：`.NET {result.get('framework_version')}`",
        f"- 目标平台：`{result.get('platform')}`",
        "",
        "## 工具构建结果",
        "",
        *build_result_rows(result),
        "",
    ]

    tools = result.get("tools", [])
    if tools:
        lines.extend(
            [
                "## 工具仓库状态",
                "",
                "| 工具 | 仓库 | 最新提交 | 检测到更新 |",
                "| --- | --- | --- | --- |",
            ]
        )
        for tool in tools:
            lines.append(
                f"| {tool.get('name')} | {tool.get('repository')} | `{tool.get('latest_revision', '-')}` | "
                f"{'是' if tool.get('updated') else '否'} |"
            )
        lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


def load_result_files(results_dir: Path) -> dict[str, dict[str, object]]:
    results: dict[str, dict[str, object]] = {}
    for file_path in sorted(results_dir.rglob("*.json")):
        data = load_json(file_path)
        branch_name = data.get("branch_name")
        if isinstance(branch_name, str) and branch_name:
            results[branch_name] = data
    return results


def status_markdown(status: dict[str, object]) -> str:
    lines = [
        "## 当前构建状态",
        "",
        f"- 最后同步时间：`{status.get('generated_at')}`",
        f"- 已配置工具数：`{status.get('summary', {}).get('tool_count', 0)}`",
        f"- 已配置目标分支数：`{status.get('summary', {}).get('branch_count', 0)}`",
        "",
        "### 工具仓库检查",
        "",
        "| 工具 | 仓库 | 最新提交 | 检测到更新 |",
        "| --- | --- | --- | --- |",
    ]
    for tool in status.get("tools", []):
        lines.append(
            f"| {tool.get('name')} | {tool.get('repository')} | `{tool.get('latest_revision', '-')}` | "
            f"{'是' if tool.get('updated') else '否'} |"
        )
    if not status.get("tools"):
        lines.append("| - | - | - | - |")

    lines.extend(
        [
            "",
            "### 目标分支构建结果",
            "",
            "| 显示名称 | Git 分支 | 状态 | 成功/失败 | 最后构建时间 |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for branch in status.get("branches", []):
        lines.append(
            f"| {branch.get('display_name')} | `{branch.get('branch')}` | {branch.get('status')} | "
            f"{branch.get('successful_targets', 0)}/{branch.get('failed_targets', 0)} | "
            f"`{branch.get('last_build_at', '-')}` |"
        )
    if not status.get("branches"):
        lines.append("| - | - | - | - | - |")

    lines.extend(
        [
            "",
            "> 说明：Git 分支名不能以 `.` 开头，因此像 `.NET_4.0_Any` 这样的显示名称会自动映射为 `NET_4.0_Any` 分支。",
        ]
    )
    return "\n".join(lines)


def update_main_readme(readme_path: Path, status: dict[str, object]) -> None:
    content = readme_path.read_text(encoding="utf-8")
    replacement = f"{README_START}\n{status_markdown(status)}\n{README_END}"
    pattern = re.compile(rf"{re.escape(README_START)}.*?{re.escape(README_END)}", re.DOTALL)
    if pattern.search(content):
        updated = pattern.sub(replacement, content)
    else:
        updated = content.rstrip() + "\n\n" + replacement + "\n"
    readme_path.write_text(updated, encoding="utf-8")


def aggregate_status(
    config_path: Path,
    results_dir: Path,
    status_output: Path,
    readme_path: Path,
    previous_status_path: Path | None,
) -> int:
    config = load_config(config_path)
    targets = configured_targets(config)
    result_files = load_result_files(results_dir)
    previous_status = load_json(previous_status_path) if previous_status_path and previous_status_path.exists() else {}
    previous_branches = {
        str(branch.get("branch")): branch
        for branch in previous_status.get("branches", [])
        if isinstance(branch, dict) and branch.get("branch")
    }

    branches: list[dict[str, object]] = []
    recorded_tools: list[dict[str, object]] = []
    for target in targets:
        result = result_files.get(target["branch"])
        if result and not recorded_tools:
            recorded_tools = list(result.get("tools", []))
        if result:
            summary = result.get("summary", {})
            branches.append(
                {
                    "branch": target["branch"],
                    "display_name": target["display_name"],
                    "framework_version": target["framework_version"],
                    "framework_moniker": target["framework_moniker"],
                    "platform": target["platform"],
                    "status": summary.get("status", "unknown"),
                    "successful_targets": summary.get("successful_targets", 0),
                    "failed_targets": summary.get("failed_targets", 0),
                    "copied_files": summary.get("copied_files", 0),
                    "last_build_at": result.get("generated_at"),
                }
            )
            continue

        previous_branch = previous_branches.get(target["branch"], {})
        branches.append(
            {
                "branch": target["branch"],
                "display_name": target["display_name"],
                "framework_version": target["framework_version"],
                "framework_moniker": target["framework_moniker"],
                "platform": target["platform"],
                "status": previous_branch.get("status", "missing"),
                "successful_targets": previous_branch.get("successful_targets", 0),
                "failed_targets": previous_branch.get("failed_targets", 0),
                "copied_files": previous_branch.get("copied_files", 0),
                "last_build_at": previous_branch.get("last_build_at", "-"),
            }
        )

    if not recorded_tools:
        recorded_tools = list(previous_status.get("tools", []))

    status = {
        "generated_at": utc_now(),
        "tools": recorded_tools,
        "branches": branches,
        "summary": {
            "tool_count": len(recorded_tools),
            "branch_count": len(branches),
        },
    }

    status_output.parent.mkdir(parents=True, exist_ok=True)
    status_output.write_text(
        json.dumps(status, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    update_main_readme(readme_path, status)
    return 0


def emit_matrix(config_path: Path, github_output: Path | None) -> int:
    config = load_config(config_path)
    matrix = {"include": configured_targets(config)}
    matrix_json = json.dumps(matrix, ensure_ascii=False)
    print(matrix_json)
    if github_output:
        with github_output.open("a", encoding="utf-8") as handle:
            handle.write(f"matrix={matrix_json}\n")
    return 0


def main() -> int:
    args = parse_args()
    if args.command == "matrix":
        return emit_matrix(args.config, args.github_output)
    if args.command == "sync-tools":
        return sync_tools(args.config, args.tools_dir, args.status_file, args.output)
    if args.command == "branch-readme":
        return write_branch_readme(args.result_json, args.output)
    if args.command == "aggregate":
        return aggregate_status(
            args.config,
            args.results_dir,
            args.status_output,
            args.readme,
            args.previous_status,
        )
    raise ValueError(f"Unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
